
type TailwindBorderClasses = 
"border-solid" |
"border-dashed" |
"border-dotted" |
"border-double" |
"border-none" |
"border" |
"border-0" |
"border-2" |
"border-4" |
"border-8" |
"border-t" |
"border-r" |
"border-b" |
"border-l" |
"border-t-0" |
"border-r-0" |
"border-b-0" |
"border-l-0" |
"border-t-2" |
"border-r-2" |
"border-b-2" |
"border-l-2" |
"border-t-4" |
"border-r-4" |
"border-b-4" |
"border-l-4" |
"border-t-8" |
"border-r-8" |
"border-b-8" |
"border-l-8" |
"border-opacity-0" |
"border-opacity-25" |
"border-opacity-50" |
"border-opacity-75" |
"border-opacity-100" |
"divide-x" |
"divide-x-0" |
"divide-x-2" |
"divide-x-4" |
"divide-x-8" |
"divide-y" |
"divide-y-0" |
"divide-y-2" |
"divide-y-4" |
"divide-y-8" |
"divide-transparent" |
"divide-current" |
"divide-black" |
"divide-white" |
"divide-gray-100" |
"divide-gray-200" |
"divide-gray-300" |
"divide-gray-400" |
"divide-gray-500" |
"divide-gray-600" |
"divide-gray-700" |
"divide-gray-800" |
"divide-gray-900" |
"divide-red-100" |
"divide-red-200" |
"divide-red-300" |
"divide-red-400" |
"divide-red-500" |
"divide-red-600" |
"divide-red-700" |
"divide-red-800" |
"divide-red-900" |
"divide-orange-100" |
"divide-orange-200" |
"divide-orange-300" |
"divide-orange-400" |
"divide-orange-500" |
"divide-orange-600" |
"divide-orange-700" |
"divide-orange-800" |
"divide-orange-900" |
"divide-yellow-100" |
"divide-yellow-200" |
"divide-yellow-300" |
"divide-yellow-400" |
"divide-yellow-500" |
"divide-yellow-600" |
"divide-yellow-700" |
"divide-yellow-800" |
"divide-yellow-900" |
"divide-green-100" |
"divide-green-200" |
"divide-green-300" |
"divide-green-400" |
"divide-green-500" |
"divide-green-600" |
"divide-green-700" |
"divide-green-800" |
"divide-green-900" |
"divide-teal-100" |
"divide-teal-200" |
"divide-teal-300" |
"divide-teal-400" |
"divide-teal-500" |
"divide-teal-600" |
"divide-teal-700" |
"divide-teal-800" |
"divide-teal-900" |
"divide-blue-100" |
"divide-blue-200" |
"divide-blue-300" |
"divide-blue-400" |
"divide-blue-500" |
"divide-blue-600" |
"divide-blue-700" |
"divide-blue-800" |
"divide-blue-900" |
"divide-indigo-100" |
"divide-indigo-200" |
"divide-indigo-300" |
"divide-indigo-400" |
"divide-indigo-500" |
"divide-indigo-600" |
"divide-indigo-700" |
"divide-indigo-800" |
"divide-indigo-900" |
"divide-purple-100" |
"divide-purple-200" |
"divide-purple-300" |
"divide-purple-400" |
"divide-purple-500" |
"divide-purple-600" |
"divide-purple-700" |
"divide-purple-800" |
"divide-purple-900" |
"divide-pink-100" |
"divide-pink-200" |
"divide-pink-300" |
"divide-pink-400" |
"divide-pink-500" |
"divide-pink-600" |
"divide-pink-700" |
"divide-pink-800" |
"divide-pink-900" |
"divide-x-reverse" |
"divide-y-reverse" |
"divide-opacity-0" |
"divide-opacity-25" |
"divide-opacity-50" |
"divide-opacity-75" |
"divide-opacity-100" |
"border-collapse" |
"border-separate" |
"rounded-none" |
"rounded-sm" |
"rounded" |
"rounded-md" |
"rounded-lg" |
"rounded-full" |
"rounded-t-none" |
"rounded-r-none" |
"rounded-b-none" |
"rounded-l-none" |
"rounded-t-sm" |
"rounded-r-sm" |
"rounded-b-sm" |
"rounded-l-sm" |
"rounded-t" |
"rounded-r" |
"rounded-b" |
"rounded-l" |
"rounded-t-md" |
"rounded-r-md" |
"rounded-b-md" |
"rounded-l-md" |
"rounded-t-lg" |
"rounded-r-lg" |
"rounded-b-lg" |
"rounded-l-lg" |
"rounded-t-full" |
"rounded-r-full" |
"rounded-b-full" |
"rounded-l-full" |
"rounded-tl-none" |
"rounded-tr-none" |
"rounded-br-none" |
"rounded-bl-none" |
"rounded-tl-sm" |
"rounded-tr-sm" |
"rounded-br-sm" |
"rounded-bl-sm" |
"rounded-tl" |
"rounded-tr" |
"rounded-br" |
"rounded-bl" |
"rounded-tl-md" |
"rounded-tr-md" |
"rounded-br-md" |
"rounded-bl-md" |
"rounded-tl-lg" |
"rounded-tr-lg" |
"rounded-br-lg" |
"rounded-bl-lg" |
"rounded-tl-full" |
"rounded-tr-full" |
"rounded-br-full" |
"rounded-bl-full" |
"border-b" |
"border-b-0" |
"border-blue-50" |
"border-gray-50" |
"border-green-50" |
"border-indigo-50" |
"border-l" |
"border-l-0" |
"border-opacity-0" |
"border-pink-50" |
"border-purple-50" |
"border-r" |
"border-r-0" |
"border-red-50" |
"border-t" |
"border-t-0" |
"border-yellow-50" |
"rounded-2xl" |
"rounded-3xl" |
"rounded-b-2xl" |
"rounded-b-3xl" |
"rounded-b-xl" |
"rounded-bl-2xl" |
"rounded-bl-3xl" |
"rounded-bl-xl" |
"rounded-br-2xl" |
"rounded-br-3xl" |
"rounded-br-xl" |
"rounded-l-2xl" |
"rounded-l-xl" |
"rounded-r-2xl" |
"rounded-r-3xl" |
"rounded-r-xl" |
"rounded-t-2xl" |
"rounded-t-3xl" |
"rounded-t-xl" |
"rounded-tl-2xl" |
"rounded-tl-3xl" |
"rounded-tl-xl" |
"rounded-tr-2xl" |
"rounded-tr-3xl" |
"rounded-tr-xl" |
"rounded-xl"


export default TailwindBorderClasses;